# Generated by Django 3.2.9 on 2021-11-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_on',)},
        ),
    ]
