# Generated by Django 3.2.9 on 2021-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='no_image.webp', upload_to='customers'),
        ),
    ]
