# Generated by Django 3.2.9 on 2021-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, default='test', max_length=12),
            preserve_default=False,
        ),
    ]
