# Generated by Django 3.2.9 on 2021-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
