# Generated by Django 3.2.9 on 2021-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20211109_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='file',
        ),
        migrations.AddField(
            model_name='csv',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='csv',
            name='sales_file',
            field=models.FileField(null=True, upload_to='csv'),
        ),
    ]
