# Generated by Django 3.2.9 on 2021-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20211111_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
